
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.zombierool.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.zombierool.item.WunderwaffeDG2WeaponItem;
import net.mcreator.zombierool.item.WhisperWeaponItem;
import net.mcreator.zombierool.item.VectorWeaponItem;
import net.mcreator.zombierool.item.VandalWeaponItem;
import net.mcreator.zombierool.item.UziWeaponItem;
import net.mcreator.zombierool.item.USP45WeaponItem;
import net.mcreator.zombierool.item.UMP45WeaponItem;
import net.mcreator.zombierool.item.TroicinqseptmagnumItem;
import net.mcreator.zombierool.item.TrenchGunWeaponItem;
import net.mcreator.zombierool.item.ThundergunWeaponItem;
import net.mcreator.zombierool.item.ThompsonWeaponItem;
import net.mcreator.zombierool.item.TAR21WeaponItem;
import net.mcreator.zombierool.item.SuperBowItem;
import net.mcreator.zombierool.item.StormWeaponItem;
import net.mcreator.zombierool.item.Stg44WeaponItem;
import net.mcreator.zombierool.item.Starr1858WeaponItem;
import net.mcreator.zombierool.item.SpringfieldWeaponItem;
import net.mcreator.zombierool.item.SniperWeaponItem;
import net.mcreator.zombierool.item.ShotgunWeaponItem;
import net.mcreator.zombierool.item.ScarHWeaponItem;
import net.mcreator.zombierool.item.SawWeaponItem;
import net.mcreator.zombierool.item.SPAS12WeaponItem;
import net.mcreator.zombierool.item.RaygunWeaponItem;
import net.mcreator.zombierool.item.RaygunMarkiiItem;
import net.mcreator.zombierool.item.RPKWeaponItem;
import net.mcreator.zombierool.item.RPGWeaponItem;
import net.mcreator.zombierool.item.RPDWeaponItem;
import net.mcreator.zombierool.item.R4CWeaponItem;
import net.mcreator.zombierool.item.PlasmaPistolWeaponItem;
import net.mcreator.zombierool.item.PercepteurWeaponItem;
import net.mcreator.zombierool.item.PPSH41Item;
import net.mcreator.zombierool.item.P90WeaponItem;
import net.mcreator.zombierool.item.OldSwordWeaponItem;
import net.mcreator.zombierool.item.OldCrossbowWeaponItem;
import net.mcreator.zombierool.item.NeedlerWeaponItem;
import net.mcreator.zombierool.item.Mp40WeaponItem;
import net.mcreator.zombierool.item.MosinNagantWeaponItem;
import net.mcreator.zombierool.item.MauserC96WeaponItem;
import net.mcreator.zombierool.item.Maschinenpistole28WeaponItem;
import net.mcreator.zombierool.item.MagnumWeaponItem;
import net.mcreator.zombierool.item.MPXWeaponItem;
import net.mcreator.zombierool.item.MP7WeaponItem;
import net.mcreator.zombierool.item.MP5WeaponItem;
import net.mcreator.zombierool.item.MG42WeaponItem;
import net.mcreator.zombierool.item.MA5DWeaponItem;
import net.mcreator.zombierool.item.M7SMGWeaponItem;
import net.mcreator.zombierool.item.M40A3WeaponItem;
import net.mcreator.zombierool.item.M1GarandItem;
import net.mcreator.zombierool.item.M1911WeaponItem;
import net.mcreator.zombierool.item.M16A4WeaponItem;
import net.mcreator.zombierool.item.M14WeaponItem;
import net.mcreator.zombierool.item.L85A2WeaponItem;
import net.mcreator.zombierool.item.Kar98kWeaponItem;
import net.mcreator.zombierool.item.InterventionWeaponItem;
import net.mcreator.zombierool.item.IngotSaleItem;
import net.mcreator.zombierool.item.HydraWeaponItem;
import net.mcreator.zombierool.item.GlockWeaponItem;
import net.mcreator.zombierool.item.Gewehr43WeaponItem;
import net.mcreator.zombierool.item.GalilWeaponItem;
import net.mcreator.zombierool.item.G36cWeaponItem;
import net.mcreator.zombierool.item.FlamethrowerWeaponItem;
import net.mcreator.zombierool.item.FiveSevenWeaponItem;
import net.mcreator.zombierool.item.FNFALWeaponItem;
import net.mcreator.zombierool.item.FG42WeaponItem;
import net.mcreator.zombierool.item.FAMASWeaponItem;
import net.mcreator.zombierool.item.EnergySwordItem;
import net.mcreator.zombierool.item.DragunovWeaponItem;
import net.mcreator.zombierool.item.DoubleBarrelWeaponItem;
import net.mcreator.zombierool.item.DeagleWeaponItem;
import net.mcreator.zombierool.item.DMRWeaponItem;
import net.mcreator.zombierool.item.CovenantCarbineWeaponItem;
import net.mcreator.zombierool.item.ChinaLakeWeaponItem;
import net.mcreator.zombierool.item.CZScorpionEvo3WeaponItem;
import net.mcreator.zombierool.item.BulletVestTier1Item;
import net.mcreator.zombierool.item.BrowningM1911WeaponItem;
import net.mcreator.zombierool.item.BloodBrushItem;
import net.mcreator.zombierool.item.BizonWeaponItem;
import net.mcreator.zombierool.item.Beretta93rWeaponItem;
import net.mcreator.zombierool.item.BattleRifleWeaponItem;
import net.mcreator.zombierool.item.BarretWeaponItem;
import net.mcreator.zombierool.item.BARWeaponItem;
import net.mcreator.zombierool.item.ArisakaWeaponItem;
import net.mcreator.zombierool.item.Arc12WeaponItem;
import net.mcreator.zombierool.item.Ak47WeaponItem;
import net.mcreator.zombierool.item.AUGWeaponItem;
import net.mcreator.zombierool.item.AK74uWeaponItem;
import net.mcreator.zombierool.item.ACRWeaponItem;
import net.mcreator.zombierool.ZombieroolMod;

public class ZombieroolModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, ZombieroolMod.MODID);
	public static final RegistryObject<Item> PATH = block(ZombieroolModBlocks.PATH);
	public static final RegistryObject<Item> DEFENSE_DOOR = doubleBlock(ZombieroolModBlocks.DEFENSE_DOOR);
	public static final RegistryObject<Item> STORAGE_BOX = block(ZombieroolModBlocks.STORAGE_BOX);
	public static final RegistryObject<Item> ZOMBIE_SPAWN_EGG = REGISTRY.register("zombie_spawn_egg", () -> new ForgeSpawnEggItem(ZombieroolModEntities.ZOMBIE, -10092442, -10092544, new Item.Properties()));
	public static final RegistryObject<Item> LIMIT = block(ZombieroolModBlocks.LIMIT);
	public static final RegistryObject<Item> DEFENSE_DOOR_OPENED = doubleBlock(ZombieroolModBlocks.DEFENSE_DOOR_OPENED);
	public static final RegistryObject<Item> RESTRICT = block(ZombieroolModBlocks.RESTRICT);
	public static final RegistryObject<Item> INGOT_SALE = REGISTRY.register("ingot_sale", () -> new IngotSaleItem());
	public static final RegistryObject<Item> OBSTACLE_DOOR = block(ZombieroolModBlocks.OBSTACLE_DOOR);
	public static final RegistryObject<Item> POWER_SWITCH = block(ZombieroolModBlocks.POWER_SWITCH);
	public static final RegistryObject<Item> ACTIVATOR = block(ZombieroolModBlocks.ACTIVATOR);
	public static final RegistryObject<Item> ALPHA_ACTIVATOR = block(ZombieroolModBlocks.ALPHA_ACTIVATOR);
	public static final RegistryObject<Item> ALPHA_RECEPTOR = block(ZombieroolModBlocks.ALPHA_RECEPTOR);
	public static final RegistryObject<Item> BETA_ACTIVATOR = block(ZombieroolModBlocks.BETA_ACTIVATOR);
	public static final RegistryObject<Item> BETA_RECEPTOR = block(ZombieroolModBlocks.BETA_RECEPTOR);
	public static final RegistryObject<Item> OMEGA_ACTIVATOR = block(ZombieroolModBlocks.OMEGA_ACTIVATOR);
	public static final RegistryObject<Item> OMEGA_RECEPTOR = block(ZombieroolModBlocks.OMEGA_RECEPTOR);
	public static final RegistryObject<Item> ULTIMA_ACTIVATOR = block(ZombieroolModBlocks.ULTIMA_ACTIVATOR);
	public static final RegistryObject<Item> ULTIMA_RECEPTOR = block(ZombieroolModBlocks.ULTIMA_RECEPTOR);
	public static final RegistryObject<Item> HELLHOUND_SPAWN_EGG = REGISTRY.register("hellhound_spawn_egg", () -> new ForgeSpawnEggItem(ZombieroolModEntities.HELLHOUND, -10066432, -16751002, new Item.Properties()));
	public static final RegistryObject<Item> CRAWLER_SPAWN_EGG = REGISTRY.register("crawler_spawn_egg", () -> new ForgeSpawnEggItem(ZombieroolModEntities.CRAWLER, -13369549, -16764109, new Item.Properties()));
	public static final RegistryObject<Item> SPAWNER_ZOMBIE = block(ZombieroolModBlocks.SPAWNER_ZOMBIE);
	public static final RegistryObject<Item> SPAWNER_CRAWLER = block(ZombieroolModBlocks.SPAWNER_CRAWLER);
	public static final RegistryObject<Item> SPAWNER_DOG = block(ZombieroolModBlocks.SPAWNER_DOG);
	public static final RegistryObject<Item> TRAITOR = block(ZombieroolModBlocks.TRAITOR);
	public static final RegistryObject<Item> BUY_WALL_WEAPON = block(ZombieroolModBlocks.BUY_WALL_WEAPON);
	public static final RegistryObject<Item> PUNCH_PACK_CORPSE = block(ZombieroolModBlocks.PUNCH_PACK_CORPSE);
	public static final RegistryObject<Item> PUNCH_PACK = block(ZombieroolModBlocks.PUNCH_PACK);
	public static final RegistryObject<Item> PERKS_LOWER = block(ZombieroolModBlocks.PERKS_LOWER);
	public static final RegistryObject<Item> PLAYER_SPAWNER = block(ZombieroolModBlocks.PLAYER_SPAWNER);
	public static final RegistryObject<Item> DECO_FARMLAND = block(ZombieroolModBlocks.DECO_FARMLAND);
	public static final RegistryObject<Item> DECO_DIRT = block(ZombieroolModBlocks.DECO_DIRT);
	public static final RegistryObject<Item> DECO_GRASS = block(ZombieroolModBlocks.DECO_GRASS);
	public static final RegistryObject<Item> DECO_STONE = block(ZombieroolModBlocks.DECO_STONE);
	public static final RegistryObject<Item> DECO_STONE_2 = block(ZombieroolModBlocks.DECO_STONE_2);
	public static final RegistryObject<Item> DECO_STONE_2_STAIRS = block(ZombieroolModBlocks.DECO_STONE_2_STAIRS);
	public static final RegistryObject<Item> DECO_STONE_2_SLAB = block(ZombieroolModBlocks.DECO_STONE_2_SLAB);
	public static final RegistryObject<Item> DECO_STONE_2_WALL = block(ZombieroolModBlocks.DECO_STONE_2_WALL);
	public static final RegistryObject<Item> DECO_PLANKS = block(ZombieroolModBlocks.DECO_PLANKS);
	public static final RegistryObject<Item> DECO_PLANKS_STAIRS = block(ZombieroolModBlocks.DECO_PLANKS_STAIRS);
	public static final RegistryObject<Item> DECO_PLANKS_SLAB = block(ZombieroolModBlocks.DECO_PLANKS_SLAB);
	public static final RegistryObject<Item> DECO_PLANKS_FENCE = block(ZombieroolModBlocks.DECO_PLANKS_FENCE);
	public static final RegistryObject<Item> WHITEBRICK = block(ZombieroolModBlocks.WHITEBRICK);
	public static final RegistryObject<Item> WHITEBRICK_STAIRS = block(ZombieroolModBlocks.WHITEBRICK_STAIRS);
	public static final RegistryObject<Item> WHITEBRICK_SLAB = block(ZombieroolModBlocks.WHITEBRICK_SLAB);
	public static final RegistryObject<Item> WHITEBRICK_WALL = block(ZombieroolModBlocks.WHITEBRICK_WALL);
	public static final RegistryObject<Item> RETRO_GRASS = block(ZombieroolModBlocks.RETRO_GRASS);
	public static final RegistryObject<Item> RETRO_GRASS_SLAB = block(ZombieroolModBlocks.RETRO_GRASS_SLAB);
	public static final RegistryObject<Item> SORCHED_GRASS = block(ZombieroolModBlocks.SORCHED_GRASS);
	public static final RegistryObject<Item> SCORCHED_GRASS_SLAB = block(ZombieroolModBlocks.SCORCHED_GRASS_SLAB);
	public static final RegistryObject<Item> SCORCHED_DIRT = block(ZombieroolModBlocks.SCORCHED_DIRT);
	public static final RegistryObject<Item> SCORCHED_DIRT_SLAB = block(ZombieroolModBlocks.SCORCHED_DIRT_SLAB);
	public static final RegistryObject<Item> OLD_MOSSY_COBBLESTONE = block(ZombieroolModBlocks.OLD_MOSSY_COBBLESTONE);
	public static final RegistryObject<Item> CARVED_SLATE = block(ZombieroolModBlocks.CARVED_SLATE);
	public static final RegistryObject<Item> CARVED_STONE = block(ZombieroolModBlocks.CARVED_STONE);
	public static final RegistryObject<Item> RETRO_GRAVEL = block(ZombieroolModBlocks.RETRO_GRAVEL);
	public static final RegistryObject<Item> MESH = block(ZombieroolModBlocks.MESH);
	public static final RegistryObject<Item> PERMAFROST_GRASS = block(ZombieroolModBlocks.PERMAFROST_GRASS);
	public static final RegistryObject<Item> PERMAFROST_ICE = block(ZombieroolModBlocks.PERMAFROST_ICE);
	public static final RegistryObject<Item> WET_DIRT = block(ZombieroolModBlocks.WET_DIRT);
	public static final RegistryObject<Item> RETRO_COBBLESTONE = block(ZombieroolModBlocks.RETRO_COBBLESTONE);
	public static final RegistryObject<Item> RETRO_COBBLESTONE_STAIRS = block(ZombieroolModBlocks.RETRO_COBBLESTONE_STAIRS);
	public static final RegistryObject<Item> RETRO_COBBLESTONE_SLAB = block(ZombieroolModBlocks.RETRO_COBBLESTONE_SLAB);
	public static final RegistryObject<Item> RETRO_COBBLESTONE_WALL = block(ZombieroolModBlocks.RETRO_COBBLESTONE_WALL);
	public static final RegistryObject<Item> OLD_COBBLESTONE = block(ZombieroolModBlocks.OLD_COBBLESTONE);
	public static final RegistryObject<Item> OLD_COBBLESTONE_STAIRS = block(ZombieroolModBlocks.OLD_COBBLESTONE_STAIRS);
	public static final RegistryObject<Item> OLD_COBBLESTONE_SLAB = block(ZombieroolModBlocks.OLD_COBBLESTONE_SLAB);
	public static final RegistryObject<Item> OLD_COBBLESTONE_WALL = block(ZombieroolModBlocks.OLD_COBBLESTONE_WALL);
	public static final RegistryObject<Item> BALSATIC_STONE = block(ZombieroolModBlocks.BALSATIC_STONE);
	public static final RegistryObject<Item> BALSATIC_STONE_STAIR = block(ZombieroolModBlocks.BALSATIC_STONE_STAIR);
	public static final RegistryObject<Item> BALSATIC_STONE_SLAB = block(ZombieroolModBlocks.BALSATIC_STONE_SLAB);
	public static final RegistryObject<Item> BALSATIC_STONE_WALL = block(ZombieroolModBlocks.BALSATIC_STONE_WALL);
	public static final RegistryObject<Item> RETRO_BRICK = block(ZombieroolModBlocks.RETRO_BRICK);
	public static final RegistryObject<Item> RETRO_BRICK_STAIR = block(ZombieroolModBlocks.RETRO_BRICK_STAIR);
	public static final RegistryObject<Item> RETRO_BRICK_SLAB = block(ZombieroolModBlocks.RETRO_BRICK_SLAB);
	public static final RegistryObject<Item> RETRO_BRICK_WALL = block(ZombieroolModBlocks.RETRO_BRICK_WALL);
	public static final RegistryObject<Item> BRICK_GRANITE = block(ZombieroolModBlocks.BRICK_GRANITE);
	public static final RegistryObject<Item> BRICK_GRANITE_STAIR = block(ZombieroolModBlocks.BRICK_GRANITE_STAIR);
	public static final RegistryObject<Item> BRICK_GRANITE_WALL = block(ZombieroolModBlocks.BRICK_GRANITE_WALL);
	public static final RegistryObject<Item> BRICK_GRANITE_SLAB = block(ZombieroolModBlocks.BRICK_GRANITE_SLAB);
	public static final RegistryObject<Item> BRICK_IRON = block(ZombieroolModBlocks.BRICK_IRON);
	public static final RegistryObject<Item> BRICK_IRON_STAIR = block(ZombieroolModBlocks.BRICK_IRON_STAIR);
	public static final RegistryObject<Item> BRICK_IRON_SLAB = block(ZombieroolModBlocks.BRICK_IRON_SLAB);
	public static final RegistryObject<Item> BRICK_IRON_WALL = block(ZombieroolModBlocks.BRICK_IRON_WALL);
	public static final RegistryObject<Item> BRICK_SLATE = block(ZombieroolModBlocks.BRICK_SLATE);
	public static final RegistryObject<Item> BRICK_SLATE_STAIRS = block(ZombieroolModBlocks.BRICK_SLATE_STAIRS);
	public static final RegistryObject<Item> BRICK_SLATE_SLAB = block(ZombieroolModBlocks.BRICK_SLATE_SLAB);
	public static final RegistryObject<Item> BRICK_SLATE_WALL = block(ZombieroolModBlocks.BRICK_SLATE_WALL);
	public static final RegistryObject<Item> BRICK_STEEL = block(ZombieroolModBlocks.BRICK_STEEL);
	public static final RegistryObject<Item> BRICK_STEEL_STAIRS = block(ZombieroolModBlocks.BRICK_STEEL_STAIRS);
	public static final RegistryObject<Item> BRICK_STEEL_SLAB = block(ZombieroolModBlocks.BRICK_STEEL_SLAB);
	public static final RegistryObject<Item> BRICK_STEEL_WALL = block(ZombieroolModBlocks.BRICK_STEEL_WALL);
	public static final RegistryObject<Item> BRICK_STONE = block(ZombieroolModBlocks.BRICK_STONE);
	public static final RegistryObject<Item> BRICK_STONE_STAIRS = block(ZombieroolModBlocks.BRICK_STONE_STAIRS);
	public static final RegistryObject<Item> BRICK_STONE_SLAB = block(ZombieroolModBlocks.BRICK_STONE_SLAB);
	public static final RegistryObject<Item> BRICK_STONE_WALL = block(ZombieroolModBlocks.BRICK_STONE_WALL);
	public static final RegistryObject<Item> STEEL_SLATE = block(ZombieroolModBlocks.STEEL_SLATE);
	public static final RegistryObject<Item> STEEL_SLATE_SLAB = block(ZombieroolModBlocks.STEEL_SLATE_SLAB);
	public static final RegistryObject<Item> SUPER_BOW = REGISTRY.register("super_bow", () -> new SuperBowItem());
	public static final RegistryObject<Item> M_16_A_4_WEAPON = REGISTRY.register("m_16_a_4_weapon", () -> new M16A4WeaponItem());
	public static final RegistryObject<Item> PERKS_UPPER = block(ZombieroolModBlocks.PERKS_UPPER);
	public static final RegistryObject<Item> PERKS_ANTENNE = block(ZombieroolModBlocks.PERKS_ANTENNE);
	public static final RegistryObject<Item> PLANKSBLACK = block(ZombieroolModBlocks.PLANKSBLACK);
	public static final RegistryObject<Item> PLANKS_BLACK_STAIRS = block(ZombieroolModBlocks.PLANKS_BLACK_STAIRS);
	public static final RegistryObject<Item> PLANKS_BLACK_FENCE = block(ZombieroolModBlocks.PLANKS_BLACK_FENCE);
	public static final RegistryObject<Item> PLANKS_BLUE = block(ZombieroolModBlocks.PLANKS_BLUE);
	public static final RegistryObject<Item> PLANKS_BLUE_STAIRS = block(ZombieroolModBlocks.PLANKS_BLUE_STAIRS);
	public static final RegistryObject<Item> PLANKS_BLUE_FENCE = block(ZombieroolModBlocks.PLANKS_BLUE_FENCE);
	public static final RegistryObject<Item> PLANKS_BROWN = block(ZombieroolModBlocks.PLANKS_BROWN);
	public static final RegistryObject<Item> PLANKS_BROWN_STAIRS = block(ZombieroolModBlocks.PLANKS_BROWN_STAIRS);
	public static final RegistryObject<Item> PLANKS_BROWN_FENCE = block(ZombieroolModBlocks.PLANKS_BROWN_FENCE);
	public static final RegistryObject<Item> PLANKS_CYAN = block(ZombieroolModBlocks.PLANKS_CYAN);
	public static final RegistryObject<Item> PLANKS_CYAN_STAIRS = block(ZombieroolModBlocks.PLANKS_CYAN_STAIRS);
	public static final RegistryObject<Item> PLANKS_CYAN_FENCE = block(ZombieroolModBlocks.PLANKS_CYAN_FENCE);
	public static final RegistryObject<Item> PLANKS_GRAY = block(ZombieroolModBlocks.PLANKS_GRAY);
	public static final RegistryObject<Item> PLANKS_GRAY_STAIRS = block(ZombieroolModBlocks.PLANKS_GRAY_STAIRS);
	public static final RegistryObject<Item> PLANKS_GRAY_FENCE = block(ZombieroolModBlocks.PLANKS_GRAY_FENCE);
	public static final RegistryObject<Item> OLD_PLANKS = block(ZombieroolModBlocks.OLD_PLANKS);
	public static final RegistryObject<Item> OLD_PLANKS_STAIRS = block(ZombieroolModBlocks.OLD_PLANKS_STAIRS);
	public static final RegistryObject<Item> OLD_PLANKS_FENCE = block(ZombieroolModBlocks.OLD_PLANKS_FENCE);
	public static final RegistryObject<Item> PLANKS_ORANGE = block(ZombieroolModBlocks.PLANKS_ORANGE);
	public static final RegistryObject<Item> PLANKS_ORANGE_STAIRS = block(ZombieroolModBlocks.PLANKS_ORANGE_STAIRS);
	public static final RegistryObject<Item> PLANKS_ORANGE_FENCE = block(ZombieroolModBlocks.PLANKS_ORANGE_FENCE);
	public static final RegistryObject<Item> PLANKS_PINK = block(ZombieroolModBlocks.PLANKS_PINK);
	public static final RegistryObject<Item> PLANKS_PINK_STAIRS = block(ZombieroolModBlocks.PLANKS_PINK_STAIRS);
	public static final RegistryObject<Item> PLANKS_PINK_FENCE = block(ZombieroolModBlocks.PLANKS_PINK_FENCE);
	public static final RegistryObject<Item> PLANKS_RED = block(ZombieroolModBlocks.PLANKS_RED);
	public static final RegistryObject<Item> PLANKS_RED_STAIRS = block(ZombieroolModBlocks.PLANKS_RED_STAIRS);
	public static final RegistryObject<Item> PLANKS_RED_FENCE = block(ZombieroolModBlocks.PLANKS_RED_FENCE);
	public static final RegistryObject<Item> PLANKS_WHITE = block(ZombieroolModBlocks.PLANKS_WHITE);
	public static final RegistryObject<Item> PLANKS_WHITE_STAIRS = block(ZombieroolModBlocks.PLANKS_WHITE_STAIRS);
	public static final RegistryObject<Item> PLANKS_WHITE_FENCE = block(ZombieroolModBlocks.PLANKS_WHITE_FENCE);
	public static final RegistryObject<Item> PLANKS_SILVER = block(ZombieroolModBlocks.PLANKS_SILVER);
	public static final RegistryObject<Item> PLANKS_SILVER_STAIRS = block(ZombieroolModBlocks.PLANKS_SILVER_STAIRS);
	public static final RegistryObject<Item> PLANKS_SILVER_FENCE = block(ZombieroolModBlocks.PLANKS_SILVER_FENCE);
	public static final RegistryObject<Item> PLANKS_YELLOW = block(ZombieroolModBlocks.PLANKS_YELLOW);
	public static final RegistryObject<Item> PLANKS_YELLOW_STAIRS = block(ZombieroolModBlocks.PLANKS_YELLOW_STAIRS);
	public static final RegistryObject<Item> PLANKS_YELLOW_FENCE = block(ZombieroolModBlocks.PLANKS_YELLOW_FENCE);
	public static final RegistryObject<Item> WHITE_KNIGHT_SPAWN_EGG = REGISTRY.register("white_knight_spawn_egg", () -> new ForgeSpawnEggItem(ZombieroolModEntities.WHITE_KNIGHT, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> RETRO_GLASS = block(ZombieroolModBlocks.RETRO_GLASS);
	public static final RegistryObject<Item> RETRO_GLASS_SLAB = block(ZombieroolModBlocks.RETRO_GLASS_SLAB);
	public static final RegistryObject<Item> RETRO_GLASS_PANE = block(ZombieroolModBlocks.RETRO_GLASS_PANE);
	public static final RegistryObject<Item> GLASS_STEEL = block(ZombieroolModBlocks.GLASS_STEEL);
	public static final RegistryObject<Item> GLASS_STEEL_SLAB = block(ZombieroolModBlocks.GLASS_STEEL_SLAB);
	public static final RegistryObject<Item> GLASS_STEEL_PANE = block(ZombieroolModBlocks.GLASS_STEEL_PANE);
	public static final RegistryObject<Item> GLASS_TINTED = block(ZombieroolModBlocks.GLASS_TINTED);
	public static final RegistryObject<Item> GLASS_TINTED_SLAB = block(ZombieroolModBlocks.GLASS_TINTED_SLAB);
	public static final RegistryObject<Item> GLASS_TINTED_PANE = block(ZombieroolModBlocks.GLASS_TINTED_PANE);
	public static final RegistryObject<Item> DARKBRICK = block(ZombieroolModBlocks.DARKBRICK);
	public static final RegistryObject<Item> DARKBRICK_STAIRS = block(ZombieroolModBlocks.DARKBRICK_STAIRS);
	public static final RegistryObject<Item> DARKBRICK_SLAB = block(ZombieroolModBlocks.DARKBRICK_SLAB);
	public static final RegistryObject<Item> DARKBRICK_WALL = block(ZombieroolModBlocks.DARKBRICK_WALL);
	public static final RegistryObject<Item> DARKBRICKVARIATION = block(ZombieroolModBlocks.DARKBRICKVARIATION);
	public static final RegistryObject<Item> OPAQUE_LEAVES = block(ZombieroolModBlocks.OPAQUE_LEAVES);
	public static final RegistryObject<Item> PURPLEWALLPAPER = block(ZombieroolModBlocks.PURPLEWALLPAPER);
	public static final RegistryObject<Item> SEWERBRICK = block(ZombieroolModBlocks.SEWERBRICK);
	public static final RegistryObject<Item> SEWERBRICK_STAIRS = block(ZombieroolModBlocks.SEWERBRICK_STAIRS);
	public static final RegistryObject<Item> SEWERBRICK_SLAB = block(ZombieroolModBlocks.SEWERBRICK_SLAB);
	public static final RegistryObject<Item> SEWERBRICK_WALL = block(ZombieroolModBlocks.SEWERBRICK_WALL);
	public static final RegistryObject<Item> SQUAREFLOOR = block(ZombieroolModBlocks.SQUAREFLOOR);
	public static final RegistryObject<Item> SQUAREFLOOR_SLAB = block(ZombieroolModBlocks.SQUAREFLOOR_SLAB);
	public static final RegistryObject<Item> MYSTERY_BOX = block(ZombieroolModBlocks.MYSTERY_BOX);
	public static final RegistryObject<Item> EMPTYMYSTERYBOX = block(ZombieroolModBlocks.EMPTYMYSTERYBOX);
	public static final RegistryObject<Item> M_1911_WEAPON = REGISTRY.register("m_1911_weapon", () -> new M1911WeaponItem());
	public static final RegistryObject<Item> TROICINQSEPTMAGNUM = REGISTRY.register("troicinqseptmagnum", () -> new TroicinqseptmagnumItem());
	public static final RegistryObject<Item> KAR_98K_WEAPON = REGISTRY.register("kar_98k_weapon", () -> new Kar98kWeaponItem());
	public static final RegistryObject<Item> MAUSER_C_96_WEAPON = REGISTRY.register("mauser_c_96_weapon", () -> new MauserC96WeaponItem());
	public static final RegistryObject<Item> GLOCK_WEAPON = REGISTRY.register("glock_weapon", () -> new GlockWeaponItem());
	public static final RegistryObject<Item> MANNEQUIN_SPAWN_EGG = REGISTRY.register("mannequin_spawn_egg", () -> new ForgeSpawnEggItem(ZombieroolModEntities.MANNEQUIN, -6724096, -26215, new Item.Properties()));
	public static final RegistryObject<Item> WHISPER_WEAPON = REGISTRY.register("whisper_weapon", () -> new WhisperWeaponItem());
	public static final RegistryObject<Item> MOSIN_NAGANT_WEAPON = REGISTRY.register("mosin_nagant_weapon", () -> new MosinNagantWeaponItem());
	public static final RegistryObject<Item> ARISAKA_WEAPON = REGISTRY.register("arisaka_weapon", () -> new ArisakaWeaponItem());
	public static final RegistryObject<Item> SPRINGFIELD_WEAPON = REGISTRY.register("springfield_weapon", () -> new SpringfieldWeaponItem());
	public static final RegistryObject<Item> USP_45_WEAPON = REGISTRY.register("usp_45_weapon", () -> new USP45WeaponItem());
	public static final RegistryObject<Item> FIVE_SEVEN_WEAPON = REGISTRY.register("five_seven_weapon", () -> new FiveSevenWeaponItem());
	public static final RegistryObject<Item> BERETTA_93R_WEAPON = REGISTRY.register("beretta_93r_weapon", () -> new Beretta93rWeaponItem());
	public static final RegistryObject<Item> DEAGLE_WEAPON = REGISTRY.register("deagle_weapon", () -> new DeagleWeaponItem());
	public static final RegistryObject<Item> M_1_GARAND = REGISTRY.register("m_1_garand", () -> new M1GarandItem());
	public static final RegistryObject<Item> GEWEHR_43_WEAPON = REGISTRY.register("gewehr_43_weapon", () -> new Gewehr43WeaponItem());
	public static final RegistryObject<Item> RAYGUN_MARKII = REGISTRY.register("raygun_markii", () -> new RaygunMarkiiItem());
	public static final RegistryObject<Item> THUNDERGUN_WEAPON = REGISTRY.register("thundergun_weapon", () -> new ThundergunWeaponItem());
	public static final RegistryObject<Item> WUNDERWAFFE_DG_2_WEAPON = REGISTRY.register("wunderwaffe_dg_2_weapon", () -> new WunderwaffeDG2WeaponItem());
	public static final RegistryObject<Item> MP_40_WEAPON = REGISTRY.register("mp_40_weapon", () -> new Mp40WeaponItem());
	public static final RegistryObject<Item> STG_44_WEAPON = REGISTRY.register("stg_44_weapon", () -> new Stg44WeaponItem());
	public static final RegistryObject<Item> THOMPSON_WEAPON = REGISTRY.register("thompson_weapon", () -> new ThompsonWeaponItem());
	public static final RegistryObject<Item> PPSH_41 = REGISTRY.register("ppsh_41", () -> new PPSH41Item());
	public static final RegistryObject<Item> BAR_WEAPON = REGISTRY.register("bar_weapon", () -> new BARWeaponItem());
	public static final RegistryObject<Item> FG_42_WEAPON = REGISTRY.register("fg_42_weapon", () -> new FG42WeaponItem());
	public static final RegistryObject<Item> TRENCH_GUN_WEAPON = REGISTRY.register("trench_gun_weapon", () -> new TrenchGunWeaponItem());
	public static final RegistryObject<Item> DOUBLE_BARREL_WEAPON = REGISTRY.register("double_barrel_weapon", () -> new DoubleBarrelWeaponItem());
	public static final RegistryObject<Item> AK_47_WEAPON = REGISTRY.register("ak_47_weapon", () -> new Ak47WeaponItem());
	public static final RegistryObject<Item> AK_74U_WEAPON = REGISTRY.register("ak_74u_weapon", () -> new AK74uWeaponItem());
	public static final RegistryObject<Item> FAMAS_WEAPON = REGISTRY.register("famas_weapon", () -> new FAMASWeaponItem());
	public static final RegistryObject<Item> SCAR_H_WEAPON = REGISTRY.register("scar_h_weapon", () -> new ScarHWeaponItem());
	public static final RegistryObject<Item> AUG_WEAPON = REGISTRY.register("aug_weapon", () -> new AUGWeaponItem());
	public static final RegistryObject<Item> TAR_21_WEAPON = REGISTRY.register("tar_21_weapon", () -> new TAR21WeaponItem());
	public static final RegistryObject<Item> FNFAL_WEAPON = REGISTRY.register("fnfal_weapon", () -> new FNFALWeaponItem());
	public static final RegistryObject<Item> ACR_WEAPON = REGISTRY.register("acr_weapon", () -> new ACRWeaponItem());
	public static final RegistryObject<Item> G_36C_WEAPON = REGISTRY.register("g_36c_weapon", () -> new G36cWeaponItem());
	public static final RegistryObject<Item> M_14_WEAPON = REGISTRY.register("m_14_weapon", () -> new M14WeaponItem());
	public static final RegistryObject<Item> GRAY_MOSAIC = block(ZombieroolModBlocks.GRAY_MOSAIC);
	public static final RegistryObject<Item> BLUE_MOSAIC = block(ZombieroolModBlocks.BLUE_MOSAIC);
	public static final RegistryObject<Item> DARK_MOSAIC = block(ZombieroolModBlocks.DARK_MOSAIC);
	public static final RegistryObject<Item> ASH_STONE = block(ZombieroolModBlocks.ASH_STONE);
	public static final RegistryObject<Item> MP_5_WEAPON = REGISTRY.register("mp_5_weapon", () -> new MP5WeaponItem());
	public static final RegistryObject<Item> UMP_45_WEAPON = REGISTRY.register("ump_45_weapon", () -> new UMP45WeaponItem());
	public static final RegistryObject<Item> BIZON_WEAPON = REGISTRY.register("bizon_weapon", () -> new BizonWeaponItem());
	public static final RegistryObject<Item> P_90_WEAPON = REGISTRY.register("p_90_weapon", () -> new P90WeaponItem());
	public static final RegistryObject<Item> VECTOR_WEAPON = REGISTRY.register("vector_weapon", () -> new VectorWeaponItem());
	public static final RegistryObject<Item> UZI_WEAPON = REGISTRY.register("uzi_weapon", () -> new UziWeaponItem());
	public static final RegistryObject<Item> RPD_WEAPON = REGISTRY.register("rpd_weapon", () -> new RPDWeaponItem());
	public static final RegistryObject<Item> RPK_WEAPON = REGISTRY.register("rpk_weapon", () -> new RPKWeaponItem());
	public static final RegistryObject<Item> GALIL_WEAPON = REGISTRY.register("galil_weapon", () -> new GalilWeaponItem());
	public static final RegistryObject<Item> INTERVENTION_WEAPON = REGISTRY.register("intervention_weapon", () -> new InterventionWeaponItem());
	public static final RegistryObject<Item> BARRET_WEAPON = REGISTRY.register("barret_weapon", () -> new BarretWeaponItem());
	public static final RegistryObject<Item> DRAGUNOV_WEAPON = REGISTRY.register("dragunov_weapon", () -> new DragunovWeaponItem());
	public static final RegistryObject<Item> M_40_A_3_WEAPON = REGISTRY.register("m_40_a_3_weapon", () -> new M40A3WeaponItem());
	public static final RegistryObject<Item> SPAS_12_WEAPON = REGISTRY.register("spas_12_weapon", () -> new SPAS12WeaponItem());
	public static final RegistryObject<Item> MP_7_WEAPON = REGISTRY.register("mp_7_weapon", () -> new MP7WeaponItem());
	public static final RegistryObject<Item> TILE_BLOCK = block(ZombieroolModBlocks.TILE_BLOCK);
	public static final RegistryObject<Item> MODERN_FURNACE = block(ZombieroolModBlocks.MODERN_FURNACE);
	public static final RegistryObject<Item> MACHINE_BLOCK = block(ZombieroolModBlocks.MACHINE_BLOCK);
	public static final RegistryObject<Item> MA_5_D_WEAPON = REGISTRY.register("ma_5_d_weapon", () -> new MA5DWeaponItem());
	public static final RegistryObject<Item> NEEDLER_WEAPON = REGISTRY.register("needler_weapon", () -> new NeedlerWeaponItem());
	public static final RegistryObject<Item> ENERGY_SWORD = REGISTRY.register("energy_sword", () -> new EnergySwordItem());
	public static final RegistryObject<Item> FLAMETHROWER_WEAPON = REGISTRY.register("flamethrower_weapon", () -> new FlamethrowerWeaponItem());
	public static final RegistryObject<Item> ZOMBIE_PASS = block(ZombieroolModBlocks.ZOMBIE_PASS);
	public static final RegistryObject<Item> MAGNUM_WEAPON = REGISTRY.register("magnum_weapon", () -> new MagnumWeaponItem());
	public static final RegistryObject<Item> PLASMA_PISTOL_WEAPON = REGISTRY.register("plasma_pistol_weapon", () -> new PlasmaPistolWeaponItem());
	public static final RegistryObject<Item> M_7_SMG_WEAPON = REGISTRY.register("m_7_smg_weapon", () -> new M7SMGWeaponItem());
	public static final RegistryObject<Item> OLD_SWORD_WEAPON = REGISTRY.register("old_sword_weapon", () -> new OldSwordWeaponItem());
	public static final RegistryObject<Item> OLD_CROSSBOW_WEAPON = REGISTRY.register("old_crossbow_weapon", () -> new OldCrossbowWeaponItem());
	public static final RegistryObject<Item> ARC_12_WEAPON = REGISTRY.register("arc_12_weapon", () -> new Arc12WeaponItem());
	public static final RegistryObject<Item> BATTLE_RIFLE_WEAPON = REGISTRY.register("battle_rifle_weapon", () -> new BattleRifleWeaponItem());
	public static final RegistryObject<Item> COVENANT_CARBINE_WEAPON = REGISTRY.register("covenant_carbine_weapon", () -> new CovenantCarbineWeaponItem());
	public static final RegistryObject<Item> DMR_WEAPON = REGISTRY.register("dmr_weapon", () -> new DMRWeaponItem());
	public static final RegistryObject<Item> HYDRA_WEAPON = REGISTRY.register("hydra_weapon", () -> new HydraWeaponItem());
	public static final RegistryObject<Item> RPG_WEAPON = REGISTRY.register("rpg_weapon", () -> new RPGWeaponItem());
	public static final RegistryObject<Item> CHINA_LAKE_WEAPON = REGISTRY.register("china_lake_weapon", () -> new ChinaLakeWeaponItem());
	public static final RegistryObject<Item> BROWNING_M_1911_WEAPON = REGISTRY.register("browning_m_1911_weapon", () -> new BrowningM1911WeaponItem());
	public static final RegistryObject<Item> MG_42_WEAPON = REGISTRY.register("mg_42_weapon", () -> new MG42WeaponItem());
	public static final RegistryObject<Item> SAW_WEAPON = REGISTRY.register("saw_weapon", () -> new SawWeaponItem());
	public static final RegistryObject<Item> STORM_WEAPON = REGISTRY.register("storm_weapon", () -> new StormWeaponItem());
	public static final RegistryObject<Item> SHOTGUN_WEAPON = REGISTRY.register("shotgun_weapon", () -> new ShotgunWeaponItem());
	public static final RegistryObject<Item> SNIPER_WEAPON = REGISTRY.register("sniper_weapon", () -> new SniperWeaponItem());
	public static final RegistryObject<Item> CZ_SCORPION_EVO_3_WEAPON = REGISTRY.register("cz_scorpion_evo_3_weapon", () -> new CZScorpionEvo3WeaponItem());
	public static final RegistryObject<Item> L_85_A_2_WEAPON = REGISTRY.register("l_85_a_2_weapon", () -> new L85A2WeaponItem());
	public static final RegistryObject<Item> MASCHINENPISTOLE_28_WEAPON = REGISTRY.register("maschinenpistole_28_weapon", () -> new Maschinenpistole28WeaponItem());
	public static final RegistryObject<Item> MPX_WEAPON = REGISTRY.register("mpx_weapon", () -> new MPXWeaponItem());
	public static final RegistryObject<Item> PERCEPTEUR_WEAPON = REGISTRY.register("percepteur_weapon", () -> new PercepteurWeaponItem());
	public static final RegistryObject<Item> R_4_C_WEAPON = REGISTRY.register("r_4_c_weapon", () -> new R4CWeaponItem());
	public static final RegistryObject<Item> STARR_1858_WEAPON = REGISTRY.register("starr_1858_weapon", () -> new Starr1858WeaponItem());
	public static final RegistryObject<Item> VANDAL_WEAPON = REGISTRY.register("vandal_weapon", () -> new VandalWeaponItem());
	public static final RegistryObject<Item> BULLET_VEST_TIER_1_CHESTPLATE = REGISTRY.register("bullet_vest_tier_1_chestplate", () -> new BulletVestTier1Item.Chestplate());
	public static final RegistryObject<Item> OBSCURIUM = block(ZombieroolModBlocks.OBSCURIUM);
	public static final RegistryObject<Item> RAW_OBSCURIUM = block(ZombieroolModBlocks.RAW_OBSCURIUM);
	public static final RegistryObject<Item> MUD = block(ZombieroolModBlocks.MUD);
	public static final RegistryObject<Item> MUD_2 = block(ZombieroolModBlocks.MUD_2);
	public static final RegistryObject<Item> MILITARY_CRATE = block(ZombieroolModBlocks.MILITARY_CRATE);
	public static final RegistryObject<Item> WUNDERFIZZ_ANTENNE = block(ZombieroolModBlocks.WUNDERFIZZ_ANTENNE);
	public static final RegistryObject<Item> DER_WUNDERFIZZ = block(ZombieroolModBlocks.DER_WUNDERFIZZ);
	public static final RegistryObject<Item> DER_WUNDERFIZZ_UPPER = block(ZombieroolModBlocks.DER_WUNDERFIZZ_UPPER);
	public static final RegistryObject<Item> IRON_STAIRS = block(ZombieroolModBlocks.IRON_STAIRS);
	public static final RegistryObject<Item> IRON_SLABS = block(ZombieroolModBlocks.IRON_SLABS);
	public static final RegistryObject<Item> AMMO_CRATE = block(ZombieroolModBlocks.AMMO_CRATE);
	public static final RegistryObject<Item> RAYGUN_WEAPON = REGISTRY.register("raygun_weapon", () -> new RaygunWeaponItem());
	public static final RegistryObject<Item> BLOOD_BRUSH = REGISTRY.register("blood_brush", () -> new BloodBrushItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}
}
