modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="zombierool"
version="1.20.11.6.0"
displayName="ZombieRool"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Cryo"

[[dependencies.zombierool]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




